=begin
#Topological Inventory

#Topological Inventory

OpenAPI spec version: 0.1.0
Contact: you@your-company.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TopologicalInventoryApiClient::IDReadOnly
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IDReadOnly' do
  before do
    # run before each test
    @instance = TopologicalInventoryApiClient::IDReadOnly.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IDReadOnly' do
    it 'should create an instance of IDReadOnly' do
      expect(@instance).to be_instance_of(TopologicalInventoryApiClient::IDReadOnly)
    end
  end
end
